### ISSUE TITLE
The site does not work. Why?

### ISSUE THREAD

**Issue by EgbertVon-Dolst** [hoontee/godot-ni-mate-motion-capture#12]
Hello! Is the project dead? Why is the official website not working? Will the project develop further?

**Comment by hoontee** [comment]
`ni-mate.com` appears to be down. I saved a copy of the installer for every supported OS but they haven't made it to this repo yet due to size.

You can still access the Windows download here:

https://web.archive.org/web/20211114072031/https://ni-mate.com/release/2.14/Delicode_NI_mate_v2.14_Installer.exe

**Comment by hoontee** [comment]
All OS installers have been added: https://github.com/hoontee/godot-ni-mate-motion-capture#readme

**Comment by Squatnet** [comment]
I might be wrong but this doesnt seem to work unless you own theh software? I installed it, yet no messages are sent? i get simply a grey nothingness in the editor dock

**Comment by hoontee** [comment]
@Squatnet Try following this tutorial from 3:41 until 8:33:
https://www.youtube.com/watch?v=1UPZtS5LVvw
